var xmlDoc=null;var xslDoc=null;var aux;var interval;var dias=0;var horas=0;var minutos=5;var segundos=0;var titulos=[];var ntitulos;var tipos=[];var pregunta;var identificador;var opciones=[];var opciones_01=[],opciones_02=[],opciones_03=[],opciones_04=[],opciones_05=[];var opciones_06=[],opciones_07=[],opciones_08=[],opciones_09=[],opciones_10=[];var opciones_11=[],opciones_12=[],opciones_13=[];var respuestas=[];var respuestas_01=[],respuestas_02=[],respuestas_03=[],respuestas_04=[],respuestas_05=[];var respuestas_06=[],respuestas_07=[],respuestas_08=[],respuestas_09=[],respuestas_10=[];var respuestas_11=[],respuestas_12=[],respuestas_13=[];var nvacias;var nseleccionadas;var nrespuestas_correctas;var nrespuestas_incorrectas;var npreguntas_acertadas;var useranswer;var vacio="</br><span>No has introducido o seleccionado ninguna respuesta.</span>";var visto_verde=" <span id='visto_verde'>&#x2714;</span>";var aspa_roja=" <span id='aspa_roja'>&#x2716;</span>";var nota;window.onload=function(){document.getElementById('seccion2').style.display="none";document.getElementById('seccion1').style.display="block";document.getElementById('tiempo').innerHTML=minutos+"m "+segundos+" s";var xhttp=new XMLHttpRequest();xhttp.onreadystatechange=function(){if(this.readyState==4&&this.status==200){gestionarXml(this)}}
xhttp.open("GET","xml/preguntas2.xml",!0);xhttp.send();var xhttp2=new XMLHttpRequest();xhttp2.onreadystatechange=function(){if(this.readyState==4&&this.status==200){xslDoc=this.responseXML}}
xhttp2.open("GET","xml/preguntas2.xsl",!0);xhttp2.send();temporizador(dias,horas,minutos,segundos);document.getElementById('formulario').onsubmit=function(){if(aux){reponerTitulos();reponerNota();corregirPrevio();if(nvacias==0){corregir();notaFinal()}
else{window.alert("Tienes preguntas sin responder todavía.")}}
else{window.alert("¡COMIENZA DE NUEVO!")}
return!1}
document.getElementById('formulario').onreset=function(){location.reload()}
document.getElementById('botonInformeFinal').onclick=function(){if(aux){reponerTitulos();reponerNota();corregirPrevio();if(nvacias==0){notaFinal();presentarInforme()}
else{window.alert("Tienes preguntas sin responder todavía.")}}
else{window.alert("¡COMIENZA DE NUEVO!")}
return!1}}
function presentarInforme(){document.getElementById('notaFinal').innerHTML=nota.toFixed(1);document.getElementById('seccion1').style.display="none";document.getElementById('seccion2').style.display="block";if(document.implementation&&document.implementation.createDocument){xsltProcessor=new XSLTProcessor();xsltProcessor.importStylesheet(xslDoc);resultDocument=xsltProcessor.transformToFragment(xmlDoc,document);document.getElementById('informeFinal').appendChild(resultDocument)}}
window.onmousedown=function(e){var el=e.target;if(el.tagName.toLowerCase()=='option'&&el.parentNode.hasAttribute('multiple')){e.preventDefault();if(el.hasAttribute('selected'))el.removeAttribute('selected');else el.setAttribute('selected','');var select=el.parentNode.cloneNode(!0);el.parentNode.parentNode.replaceChild(select,el.parentNode)}}
function gestionarXml(dadesXml){xmlDoc=dadesXml.responseXML;mostrarTitulos();mostrarPreguntas()}
function mostrarTitulos(){ntitulos=xmlDoc.getElementsByTagName('title').length;for(var i=0;i<ntitulos;i++){titulos[i]=xmlDoc.getElementsByTagName('title')[i].innerHTML;tipos[i]=xmlDoc.getElementsByTagName('type')[i].innerHTML;document.getElementsByTagName('form')[0].innerHTML+="<h3>"+titulos[i]+"</h3><div></div>"}}
function inicializarPregunta(){opciones=[];respuestas=[]}
function inicializarNSeleccionadas(){nseleccionadas=0}
function inicializarNRespuestas(){nrespuestas_correctas=0;nrespuestas_incorrectas=0}
function inicializarNAcertadas(){npreguntas_acertadas=0}
function inicializarNVacias(){nvacias=0}
function identificadorPregunta(){if(pregunta<10){identificador='jklm_00'+pregunta}
else{identificador='jklm_0'+pregunta}}
function mostrarPreguntas(){for(var i=0;i<ntitulos;i++){pregunta=i+1;identificadorPregunta();switch(tipos[i]){case "radio":preguntaRadio();break;case "text":preguntaTexto();break;case "checkbox":preguntaCheckbox();break;case "select":preguntaSelect();break;case "multiple":preguntaSelectMultiple();break;default:window.alert("Tipo de pregunta no clasificada.");break}
switch(pregunta){case 1:opciones_01=opciones;respuestas_01=respuestas;break;case 2:opciones_02=opciones;respuestas_02=respuestas;break;case 3:opciones_03=opciones;respuestas_03=respuestas;break;case 4:opciones_04=opciones;respuestas_04=respuestas;break;case 5:opciones_05=opciones;respuestas_05=respuestas;break;case 6:opciones_06=opciones;respuestas_06=respuestas;break;case 7:opciones_07=opciones;respuestas_07=respuestas;break;case 8:opciones_08=opciones;respuestas_08=respuestas;break;case 9:opciones_09=opciones;respuestas_09=respuestas;break;case 10:opciones_10=opciones;respuestas_10=respuestas;break;case 11:opciones_11=opciones;respuestas_11=respuestas;break;case 12:opciones_12=opciones;respuestas_12=respuestas;break;case 13:opciones_13=opciones;respuestas_13=respuestas;break;default:window.alert("Número de pregunta incorrecto.");break}}}
function preguntaRadio(){inicializarPregunta();var xpath="/questions/question[@id='"+identificador+"']/option";var nodos=xmlDoc.evaluate(xpath,xmlDoc,null,XPathResult.ANY_TYPE,null);var nopciones=nodos.count;var nodo=nodos.iterateNext();var i=0;while(nodo){opciones[i]=nodo.innerHTML;document.getElementsByTagName('div')[pregunta-1].innerHTML+="<input type='radio' id = '"+identificador+"_"+i+"' name="+identificador+" value='"+i+"'><label for = '"+identificador+"_"+i+"'>"+opciones[i]+"</label><br>";nodo=nodos.iterateNext();i++}
var xpath2="/questions/question[@id='"+identificador+"']/answer";var nodos2=xmlDoc.evaluate(xpath2,xmlDoc,null,XPathResult.ANY_TYPE,null);var nrespuestas=nodos2.count;var nodo2=nodos2.iterateNext();var i=0;while(nodo2){respuestas[i]=nodo2.innerHTML;nodo2=nodos2.iterateNext();i++}}
function preguntaTexto(){inicializarPregunta();opciones=[];document.getElementsByTagName('div')[pregunta-1].innerHTML+="Respuesta: <input type='text' name="+identificador+"><br>";var xpath2="/questions/question[@id='"+identificador+"']/answer";var nodos2=xmlDoc.evaluate(xpath2,xmlDoc,null,XPathResult.ANY_TYPE,null);var nrespuestas=nodos2.count;var nodo2=nodos2.iterateNext();var i=0;while(nodo2){respuestas[i]=nodo2.innerHTML;nodo2=nodos2.iterateNext();i++}}
function preguntaCheckbox(){inicializarPregunta();var xpath="/questions/question[@id='"+identificador+"']/option";var nodos=xmlDoc.evaluate(xpath,xmlDoc,null,XPathResult.ANY_TYPE,null);var nopciones=nodos.count;var nodo=nodos.iterateNext();var i=0;while(nodo){opciones[i]=nodo.innerHTML;document.getElementsByTagName('div')[pregunta-1].innerHTML+="<input type='checkbox' id = '"+identificador+"_"+i+"' name="+identificador+" value='"+i+"'><label for = '"+identificador+"_"+i+"'>"+opciones[i]+"</label><br>";nodo=nodos.iterateNext();i++}
var xpath2="/questions/question[@id='"+identificador+"']/answer";var nodos2=xmlDoc.evaluate(xpath2,xmlDoc,null,XPathResult.ANY_TYPE,null);var nrespuestas=nodos2.count;var nodo2=nodos2.iterateNext();var i=0;while(nodo2){respuestas[i]=nodo2.innerHTML;nodo2=nodos2.iterateNext();i++}}
function preguntaSelect(){inicializarPregunta();var xpath="/questions/question[@id='"+identificador+"']/option";var nodos=xmlDoc.evaluate(xpath,xmlDoc,null,XPathResult.ANY_TYPE,null);var nopciones=nodos.count;var select=document.createElement('select');select.name=identificador;var nodo=nodos.iterateNext();var i=0;while(nodo){opciones[i]=nodo.innerHTML;var option=document.createElement('option');option.text=opciones[i];option.value=i;select.options.add(option);nodo=nodos.iterateNext();i++}
i=nopciones;opciones[i]="";var option=document.createElement('option');option.text=opciones[i];option.value=opciones[i];option.setAttribute("selected","selected");select.options.add(option);document.getElementsByTagName('div')[pregunta-1].appendChild(select);var xpath2="/questions/question[@id='"+identificador+"']/answer";var nodos2=xmlDoc.evaluate(xpath2,xmlDoc,null,XPathResult.ANY_TYPE,null);var nrespuestas=nodos2.count;var nodo2=nodos2.iterateNext();var i=0;while(nodo2){respuestas[i]=nodo2.innerHTML;nodo2=nodos2.iterateNext();i++}}
function preguntaSelectMultiple(){inicializarPregunta();var xpath="/questions/question[@id='"+identificador+"']/option";var nodos=xmlDoc.evaluate(xpath,xmlDoc,null,XPathResult.ANY_TYPE,null);var nopciones=nodos.count;var select=document.createElement('select');select.setAttribute("multiple","multiple");select.name=identificador;var nodo=nodos.iterateNext();var i=0;while(nodo){opciones[i]=nodo.innerHTML;var option=document.createElement('option');option.text=opciones[i];option.value=i;select.options.add(option);nodo=nodos.iterateNext();i++}
document.getElementsByTagName('div')[pregunta-1].appendChild(select);var xpath2="/questions/question[@id='"+identificador+"']/answer";var nodos2=xmlDoc.evaluate(xpath2,xmlDoc,null,XPathResult.ANY_TYPE,null);var nrespuestas=nodos2.count;var nodo2=nodos2.iterateNext();var i=0;while(nodo2){respuestas[i]=nodo2.innerHTML;nodo2=nodos2.iterateNext();i++}}
function corregirPrevio(){inicializarNAcertadas();inicializarNVacias();for(var i=0;i<ntitulos;i++){pregunta=i+1;identificadorPregunta();switch(pregunta){case 1:opciones=opciones_01;respuestas=respuestas_01;break;case 2:opciones=opciones_02;respuestas=respuestas_02;break;case 3:opciones=opciones_03;respuestas=respuestas_03;break;case 4:opciones=opciones_04;respuestas=respuestas_04;break;case 5:opciones=opciones_05;respuestas=respuestas_05;break;case 6:opciones=opciones_06;respuestas=respuestas_06;break;case 7:opciones=opciones_07;respuestas=respuestas_07;break;case 8:opciones=opciones_08;respuestas=respuestas_08;break;case 9:opciones=opciones_09;respuestas=respuestas_09;break;case 10:opciones=opciones_10;respuestas=respuestas_10;break;case 11:opciones=opciones_11;respuestas=respuestas_11;break;case 12:opciones=opciones_12;respuestas=respuestas_12;break;case 13:opciones=opciones_13;respuestas=respuestas_13;break;default:window.alert("Número de pregunta incorrecto.");break}
switch(tipos[i]){case "radio":opciones=document.getElementsByName(identificador);comprobacionChequeo();break;case "checkbox":opciones=document.getElementsByName(identificador);comprobacionChequeo();break;case "text":opciones=document.getElementsByName(identificador);comprobacionTexto();break;case "select":opciones=document.getElementsByName(identificador)[0].options;comprobacionSeleccion();break;case "multiple":opciones=document.getElementsByName(identificador)[0].options;comprobacionSeleccion();break;default:window.alert("Tipo de pregunta desconocido.");break}
resolucionPrevia()}}
function corregir(){inicializarNAcertadas();inicializarNVacias();for(var i=0;i<ntitulos;i++){pregunta=i+1;identificadorPregunta();switch(pregunta){case 1:opciones=opciones_01;respuestas=respuestas_01;break;case 2:opciones=opciones_02;respuestas=respuestas_02;break;case 3:opciones=opciones_03;respuestas=respuestas_03;break;case 4:opciones=opciones_04;respuestas=respuestas_04;break;case 5:opciones=opciones_05;respuestas=respuestas_05;break;case 6:opciones=opciones_06;respuestas=respuestas_06;break;case 7:opciones=opciones_07;respuestas=respuestas_07;break;case 8:opciones=opciones_08;respuestas=respuestas_08;break;case 9:opciones=opciones_09;respuestas=respuestas_09;break;case 10:opciones=opciones_10;respuestas=respuestas_10;break;case 11:opciones=opciones_11;respuestas=respuestas_11;break;case 12:opciones=opciones_12;respuestas=respuestas_12;break;case 13:opciones=opciones_13;respuestas=respuestas_13;break;default:window.alert("Número de pregunta incorrecto.");break}
switch(tipos[i]){case "radio":opciones=document.getElementsByName(identificador);comprobacionChequeo();break;case "checkbox":opciones=document.getElementsByName(identificador);comprobacionChequeo();break;case "text":opciones=document.getElementsByName(identificador);comprobacionTexto();break;case "select":opciones=document.getElementsByName(identificador)[0].options;comprobacionSeleccion();break;case "multiple":opciones=document.getElementsByName(identificador)[0].options;comprobacionSeleccion();break;default:window.alert("Tipo de pregunta desconocido.");break}
resolucion()}}
function comprobacionSeleccion(){inicializarNSeleccionadas();inicializarNRespuestas();for(var i=0;i<opciones.length;i++){if(opciones[i].selected&&opciones[i].value!=""){nseleccionadas++;useranswer=xmlDoc.createElement("useranswer");useranswer.innerHTML=opciones[i].value;xmlDoc.getElementById(identificador).appendChild(useranswer)}
for(var j=0;j<respuestas.length;j++){if(opciones[i].selected&&opciones[i].value==respuestas[j]){nrespuestas_correctas++}}}
nrespuestas_incorrectas=nseleccionadas-nrespuestas_correctas}
function comprobacionChequeo(){inicializarNSeleccionadas();inicializarNRespuestas();for(var i=0;i<opciones.length;i++){if(opciones[i].checked&&opciones[i].value!=""){nseleccionadas++;useranswer=xmlDoc.createElement("useranswer");useranswer.innerHTML=opciones[i].value;xmlDoc.getElementById(identificador).appendChild(useranswer)}
for(var j=0;j<respuestas.length;j++){if(opciones[i].checked&&opciones[i].value==respuestas[j]){nrespuestas_correctas++}}}
nrespuestas_incorrectas=nseleccionadas-nrespuestas_correctas}
function comprobacionTexto(){inicializarNSeleccionadas();inicializarNRespuestas();for(var i=0;i<opciones.length;i++){if(opciones[i].value!=""){nseleccionadas++;useranswer=xmlDoc.createElement("useranswer");useranswer.innerHTML=opciones[i].value;xmlDoc.getElementById(identificador).appendChild(useranswer)}
for(var j=0;j<respuestas.length;j++){if(opciones[i].value==respuestas[j]){nrespuestas_correctas++}}}
nrespuestas_incorrectas=nseleccionadas-nrespuestas_correctas}
function resolucionPrevia(){if(nrespuestas_correctas==0&&nrespuestas_incorrectas==0){document.getElementsByTagName('h3')[pregunta-1].innerHTML+=vacio;nvacias++}
else{if(nrespuestas_correctas==respuestas.length&&nrespuestas_incorrectas==0){npreguntas_acertadas++}}}
function resolucion(){if(nrespuestas_correctas==0&&nrespuestas_incorrectas==0){document.getElementsByTagName('h3')[pregunta-1].innerHTML+=vacio;nvacias++}
else{if(nrespuestas_correctas==respuestas.length&&nrespuestas_incorrectas==0){document.getElementsByTagName('h3')[pregunta-1].innerHTML+=visto_verde;npreguntas_acertadas++}
else{document.getElementsByTagName('h3')[pregunta-1].innerHTML+=aspa_roja+"</br><span>Aciertos "+nrespuestas_correctas+"/"+respuestas.length+". Fallos "+nrespuestas_incorrectas+".</span>"}}}
function respuestasUsuario(){var useranswer=xmlDoc.createElement("useranswer");for(var i=0;i<opciones.length;i++){if(opciones[i].value!=""){useranswer.innerHTML=opciones[i].value}
xmlDoc.getElementById(identificador).appendChild(useranswer)}}
function notaFinal(){nota=npreguntas_acertadas/ntitulos*10;document.getElementById('nota').innerHTML=nota.toFixed(1);if(npreguntas_acertadas==ntitulos){aux=!1;clearInterval(interval);window.alert("Enhorabuena, ¡has acertado todas las preguntas del test de historia!")}}
function reponerTitulos(){for(var i=0;i<ntitulos;i++){document.getElementsByTagName('h3')[i].innerHTML=titulos[i]}}
function reponerNota(){document.getElementById('nota').innerHTML="nota"}
function temporizador(d,h,m,s){aux=!0;interval=setInterval(function(){if(s>0){s--}
else{if(m>0)
{m--;s=59}
else{if(h>0)
{h--;m=59;s=59}
else{if(d>0)
{d--;h=24;m=59;s=59}
else{clearInterval(interval)}}}}
document.getElementById('tiempo').innerHTML=m+"m "+s+" s";if(d==0&&h==0&&m==0&&s==0&&aux){aux=!1;window.alert("Oh, ¡se te acabó el tiempo sin haber podido acertar todas las preguntas!");window.alert("Si quieres volver a intentarlo, ¡COMIENZA DE NUEVO!")}},1000)}
